import { fireEvent, render, screen, within } from "@testing-library/react";
import { afterEach, describe, expect, it, vi } from "vitest";
import Home from "./page";
import { fixture } from "../test/fixture";
import type { AnalysisResponse } from "../types/api";

const makeFile = (name = "sample.csv", bytes = 10) => new File([new Uint8Array(bytes)], name);
const success = (value: AnalysisResponse = fixture) => new Response(JSON.stringify(value), { status: 200, headers: { "Content-Type": "application/json" } });
const failure = (code: string, status = 400) => new Response(JSON.stringify({ error: { code, message: "SECRET_BACKEND_DETAIL" } }), { status, headers: { "Content-Type": "application/json" } });
const choose = (name = "sample.csv", bytes = 10) => fireEvent.change(screen.getByLabelText(/choose a csv/i), { target: { files: [makeFile(name, bytes)] } });
const submit = () => fireEvent.click(screen.getByRole("button", { name: "Analyze dataset" }));
const sectionByHeading = (name: string) => {
  const section = screen.getByRole("heading", { name }).closest("section");
  if (!section) throw new Error(`Section not found: ${name}`);
  return section;
};
const articleByHeading = (name: string) => {
  const article = screen.getByRole("heading", { name }).closest("article");
  if (!article) throw new Error(`Article not found: ${name}`);
  return article;
};

afterEach(() => { vi.restoreAllMocks(); vi.unstubAllGlobals(); });

describe("V0.1 analysis flow", () => {
  it("renders upload and disables Analyze initially", () => { render(<Home />); expect(screen.getByText(/understand the quality/i)).toBeInTheDocument(); expect(screen.getByRole("button", { name: "Analyze dataset" })).toBeDisabled(); });
  it("accepts CSV selection", () => { render(<Home />); choose("customers.csv"); expect(screen.getByText("customers.csv")).toBeInTheDocument(); expect(screen.getByRole("button", { name: "Analyze dataset" })).toBeEnabled(); });
  it("accepts XLSX selection", () => { render(<Home />); choose("customers.xlsx"); expect(screen.getByText("customers.xlsx")).toBeInTheDocument(); expect(screen.getByRole("button", { name: "Analyze dataset" })).toBeEnabled(); });
  it("rejects unsupported extensions without calling API", () => { const fetch = vi.fn(); vi.stubGlobal("fetch", fetch); render(<Home />); choose("customers.pdf"); expect(screen.getByText("Upload a CSV or XLSX file.")).toBeInTheDocument(); expect(fetch).not.toHaveBeenCalled(); });
  it("rejects files over 5 MiB without calling API", () => { const fetch = vi.fn(); vi.stubGlobal("fetch", fetch); render(<Home />); choose("large.csv", 5 * 1024 * 1024 + 1); expect(screen.getByText("Files must be 5 MiB or smaller.")).toBeInTheDocument(); expect(fetch).not.toHaveBeenCalled(); });
  it("removes the selected file and returns to idle", () => { render(<Home />); choose("customers.csv"); fireEvent.click(screen.getByRole("button", { name: "Remove" })); expect(screen.getByRole("button", { name: "Analyze dataset" })).toBeDisabled(); expect(screen.queryByText("customers.csv")).not.toBeInTheDocument(); });
  it("keeps controls disabled while submitting", async () => { let resolve!: (r: Response) => void; vi.stubGlobal("fetch", vi.fn(() => new Promise<Response>(r => { resolve = r; }))); render(<Home />); choose("customers.csv"); submit(); expect(await screen.findByRole("status")).toHaveTextContent("Analyzing dataset…"); expect(screen.getByLabelText(/choose a csv/i)).toBeDisabled(); expect(screen.getByRole("button", { name: "Analyzing dataset…" })).toBeDisabled(); resolve(success()); });
  it("renders overview and result navigation on success", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue(success())); render(<Home />); choose("customers.csv"); submit(); expect(await screen.findByText("Analysis complete")).toBeInTheDocument(); expect(screen.getByText("sample.csv")).toBeInTheDocument(); expect(screen.getAllByText("3").length).toBeGreaterThan(0); for (const text of ["Overview", "Quality", "Governance", "Recommendations", "Columns"]) expect(screen.getByRole("link", { name: text })).toBeInTheDocument(); });
  it("renders applicable numeric quality score", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue(success())); render(<Home />); choose(); submit(); await screen.findByText("Analysis complete"); const quality = within(sectionByHeading("Quality")); expect(quality.getByText("82")).toBeInTheDocument(); expect(quality.getByText("/ 100")).toBeInTheDocument(); });
  it("renders non-applicable quality as N/A, never zero", async () => { const value = { ...fixture, analysis: { ...fixture.analysis, quality: { ...fixture.analysis.quality, overall_score: null } } }; vi.stubGlobal("fetch", vi.fn().mockResolvedValue(success(value))); render(<Home />); choose(); submit(); await screen.findByText("Analysis complete"); expect(screen.getByText("N/A")).toBeInTheDocument(); expect(screen.queryByText("0 / 100")).not.toBeInTheDocument(); });
  it("renders exact empty finding wording", async () => { const value = { ...fixture, analysis: { ...fixture.analysis, profiling: { ...fixture.analysis.profiling, findings: [] }, quality: { ...fixture.analysis.quality, findings: [] }, governance: { ...fixture.analysis.governance, findings: [], classifications: [] } } }; vi.stubGlobal("fetch", vi.fn().mockResolvedValue(success(value))); render(<Home />); choose(); submit(); await screen.findByText("Analysis complete"); expect(screen.getAllByText("No findings were produced by the current V0.1 rules.").length).toBeGreaterThan(0); });
  it("renders quality and governance findings with semantics", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue(success())); render(<Home />); choose(); submit(); await screen.findByText("Analysis complete"); const qualityFindings = within(sectionByHeading("Quality findings")); const governanceFindings = within(sectionByHeading("Governance findings")); expect(qualityFindings.getByRole("heading", { name: "Missing values" })).toBeInTheDocument(); expect(qualityFindings.getByText("Warning")).toBeInTheDocument(); expect(qualityFindings.getByText("Detected")).toBeInTheDocument(); expect(qualityFindings.getByText("High confidence")).toBeInTheDocument(); expect(governanceFindings.getByRole("heading", { name: "Potential contact field" })).toBeInTheDocument(); expect(governanceFindings.getByText("Info")).toBeInTheDocument(); expect(governanceFindings.getByText("Inferred")).toBeInTheDocument(); });
  it("opens contextual evidence disclosure", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue(success())); render(<Home />); choose(); submit(); await screen.findByText("Analysis complete"); const finding = within(articleByHeading("Missing values")); const disclosure = finding.getByText("Why this was flagged"); const details = disclosure.closest("details"); expect(details).not.toHaveAttribute("open"); fireEvent.click(disclosure); expect(details).toHaveTextContent("Null Ratio: 0.333 / 3"); expect(finding.getByText(/Rule Q-1/)).toBeInTheDocument(); });
  it("renders recommendations and finding traceability", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue(success())); render(<Home />); choose(); submit(); await screen.findByText("Analysis complete"); const recommendation = within(articleByHeading("Review email handling")); expect(recommendation.getByText("P1")).toBeInTheDocument(); expect(recommendation.getByText("A governance signal warrants review.")).toBeInTheDocument(); fireEvent.click(recommendation.getByText("Why this recommendation?")); expect(recommendation.getByText("Potential contact field")).toBeInTheDocument(); expect(recommendation.getByText(/Rule G-1/)).toBeInTheDocument(); });
  it("filters columns by name", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue(success())); render(<Home />); choose(); submit(); await screen.findByText("Analysis complete"); const columns = within(sectionByHeading("Column inventory")); fireEvent.change(columns.getByPlaceholderText("Column name"), { target: { value: "email" } }); const table = within(columns.getByRole("table")); expect(table.getByRole("rowheader", { name: "email" })).toBeInTheDocument(); expect(table.queryByRole("rowheader", { name: "customer_id" })).not.toBeInTheDocument(); });
  it("filters columns by classification", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue(success())); render(<Home />); choose(); submit(); await screen.findByText("Analysis complete"); const columns = within(sectionByHeading("Column inventory")); fireEvent.change(columns.getByLabelText("Classification"), { target: { value: "POTENTIAL_PERSONAL_DATA" } }); const table = within(columns.getByRole("table")); expect(table.getByRole("rowheader", { name: "email" })).toBeInTheDocument(); expect(table.queryByRole("rowheader", { name: "customer_id" })).not.toBeInTheDocument(); });
  it("maps API and network failures safely", async () => { vi.stubGlobal("fetch", vi.fn().mockRejectedValue(new Error("secret stack trace"))); render(<Home />); choose(); submit(); expect(await screen.findByText("We couldn't reach the analysis service.")).toBeInTheDocument(); expect(screen.queryByText("secret stack trace")).not.toBeInTheDocument(); });
  it.each([
    ["request_too_large", "The upload request is too large. Choose a smaller file.", 413],
    ["invalid_request", "The upload request was invalid. Choose the file again.", 422],
    ["sheet_not_applicable", "Sheet selection is only available for XLSX files.", 400],
  ])("maps %s to safe actionable copy", async (code, message, status) => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue(failure(code, status))); render(<Home />); choose(); submit(); expect(await screen.findByText(message)).toBeInTheDocument(); expect(screen.queryByText("SECRET_BACKEND_DETAIL")).not.toBeInTheDocument(); });
  it("resets successful results for another dataset", async () => { vi.stubGlobal("fetch", vi.fn().mockResolvedValue(success())); render(<Home />); choose(); submit(); await screen.findByText("Analysis complete"); fireEvent.click(screen.getByRole("button", { name: "Analyze another dataset" })); expect(screen.getByText(/understand the quality/i)).toBeInTheDocument(); expect(screen.queryByText("Analysis complete")).not.toBeInTheDocument(); });
});
